spring:
  application:
    name: example-spring-boot-maven-app
  liquibase:
    parameters:
      textColumnType: VARCHAR(255)
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
