spring:
  application:
    name: example-spring-boot-maven-app
  liquibase:
    parameters:
      textColumnType: VARCHAR(255)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
management:
  datadog:
    metrics:
      export:
        enabled: false
