#!/bin/sh
echo '[git hook] executing spotless:apply to format code before commit'

# Run spotless:apply
if command -v mvn > /dev/null 2>&1
then
    mvn spotless:apply
else
  ./mvnw spotless:apply
fi

# Store the last exit code in a variable
RESULT=$?

# Stage formatting changes
git add -u

# Return the 'spotless:apply' exit code
exit $RESULT
